name: CI
on:
- pull_request
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build Pages
      run: |
        npm install
        npm run dev:build
        cat dist/index.html
        cat rounds-check-result